const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..'),dir=path.join(root,'finance/daily');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function inline(text){const links=[];text=text.replace(/\[([^\]]+)\]\((https?:\/\/[^\s]+?)\)/g,(_,label,url)=>{links.push(`<a href="${esc(url)}" rel="noopener noreferrer">${esc(label)}</a>`);return `\u0000${links.length-1}\u0000`;});return esc(text).replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\u0000(\d+)\u0000/g,(_,n)=>links[+n]);}
function markdown(body){const lines=body.replace(/\r/g,'').split('\n'),out=[];let i=0;while(i<lines.length){let l=lines[i].trim();if(!l){i++;continue;}
if(l.startsWith('|')&&/^\|[\s:|-]+\|$/.test((lines[i+1]||'').trim())){const cells=s=>s.trim().replace(/^\||\|$/g,'').split('|').map(x=>inline(x.trim()));const heads=cells(l);i+=2;let rows='';while(i<lines.length&&lines[i].trim().startsWith('|')){rows+='<tr>'+cells(lines[i++]).map(c=>'<td>'+c+'</td>').join('')+'</tr>';}out.push('<div class="table-scroll" role="region" aria-label="财经数据表，可横向滚动" tabindex="0"><table><thead><tr>'+heads.map(c=>'<th scope="col">'+c+'</th>').join('')+'</tr></thead><tbody>'+rows+'</tbody></table></div>');continue;}
if(/^[-*] /.test(l)){let list='';while(i<lines.length&&/^[-*] /.test(lines[i].trim()))list+='<li>'+inline(lines[i++].trim().slice(2))+'</li>';out.push('<ul>'+list+'</ul>');continue;}
const heading=l.match(/^(#{1,6})\s+(.+)$/);if(heading){const level=Math.max(2,heading[1].length);out.push(`<h${level}>${inline(heading[2])}</h${level}>`);i++;continue;}
if(/^\*\*[^*]+\*\*$/.test(l)&&l.length<85){out.push('<h2>'+inline(l.slice(2,-2))+'</h2>');i++;continue;}
let paragraph=[l];i++;while(i<lines.length&&lines[i].trim()&&!/^(\||[-*] |#)/.test(lines[i].trim()))paragraph.push(lines[i++].trim());out.push('<p>'+inline(paragraph.join(' '))+'</p>');}return out.join('\n');}
const files=fs.readdirSync(path.join(dir,'data')).filter(f=>/^\d{4}-\d{2}-\d{2}\.json$/.test(f));const reports=files.map(f=>{const r=JSON.parse(fs.readFileSync(path.join(dir,'data',f),'utf8'));if(r.date+'.json'!==f||!r.title||!r.body||!r.cutoff||!r.summary)throw Error('Invalid report '+f);const date=new Date(r.date+'T00:00:00Z');if(!Number.isFinite(+date)||date.toISOString().slice(0,10)!==r.date)throw Error('Invalid date');return r;}).sort((a,b)=>b.date.localeCompare(a.date));
function shell(title,content){return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} · 兴耀未来</title><meta name="description" content="每日财经：按日期归档全球市场、财经事件与风险观察。"><link rel="stylesheet" href="../../style.css"></head><body class="theme-finance"><a class="skip" href="#daily-content">跳到正文</a><header class="wrap"><a class="brand" href="../../index.html"><span class="mark">兴</span>兴耀未来</a><nav><a href="../../finance.html">投资理财</a><a href="index.html">每日财经</a></nav></header><main class="wrap daily-main" id="daily-content"><div class="breadcrumb"><a href="../../index.html">首页</a><span>/</span><a href="../../finance.html">投资理财</a><span>/</span><a href="index.html">每日财经</a></div>${content}</main><footer class="wrap"><a href="index.html">每日财经目录</a><span>兴耀未来 · 持续记录</span></footer><script src="../../theme-motion.js" defer></script></body></html>`;}
for(const [i,r] of reports.entries()){const paging=[reports[i+1]&&`<a href="${reports[i+1].date}.html">← ${reports[i+1].date}</a>`,reports[i-1]&&`<a href="${reports[i-1].date}.html">${reports[i-1].date} →</a>`].filter(Boolean).join('');fs.writeFileSync(path.join(dir,r.date+'.html'),shell(r.date+' 每日财经',`<div class="daily-heading"><span class="eyebrow">DAILY FINANCE / ${esc(r.edition||'财经日报')}</span><h1>${esc(r.title)}</h1><p><time datetime="${r.date}">${r.date}</time> · 数据截止：${esc(r.cutoff)}</p></div><p class="report-note">本页为当日报告归档，行情与判断仅对应报告标注时点。历史报告未按当前行情重新核验。</p><article class="report-body">${markdown(r.body)}</article><nav class="daily-pagination" aria-label="相邻日期">${paging}</nav>`));}
const cards=reports.map(r=>`<article class="daily-entry"><time datetime="${r.date}">${r.date}</time><div><span class="eyebrow">${esc(r.edition||'财经日报')}</span><h2><a href="${r.date}.html">${esc(r.title)} ↗</a></h2><p>${esc(r.summary)}</p><span class="post-date">数据截止：${esc(r.cutoff)}</span></div></article>`).join('\n');
fs.writeFileSync(path.join(dir,'index.html'),shell('每日财经',`<section class="daily-heading daily-photo-heading"><img class="theme-image daily-hero-image" src="../../assets/daily-finance.png" width="1672" height="941" alt="全球市场、城市天际线与行情走势组成的每日财经图景" fetchpriority="high" decoding="async"><div class="daily-heading-top"><span class="eyebrow">DAILY FINANCE / 08:00</span><button class="motion-toggle" type="button" aria-pressed="false">暂停动效</button></div><h1>每日财经</h1><p>每天一份市场记录，按日期回看财经事件、全球市场与风险观察。</p><div class="subject-labels"><span>全球市场</span><span>重要事件</span><span>板块观察</span></div></section><div class="section-title daily-list-title"><h2>按日期归档</h2><span>${reports.length} 期 · 最新在前</span></div>${cards||'<p>首份报告准备中。</p>'}`));
// Only replace the marked daily section; other finance content remains intact.
let finance=fs.readFileSync(path.join(root,'finance.html'),'utf8');const block=`<!-- DAILY-FINANCE-START --><div class="section-title"><h2>每日财经</h2><span>${reports.length} 期报告</span></div><a class="daily-channel-card daily-photo-card" href="finance/daily/index.html"><img class="theme-image daily-card-image" src="assets/daily-finance.png" width="1672" height="941" alt="" loading="lazy" decoding="async"><span class="eyebrow">DAILY FINANCE / 每日 08:00</span><h2>用一份日报，看清市场脉络。 <span>↗</span></h2><p>财经事件、全球市场表现、板块机会与风险，按日期持续归档。</p><strong>进入每日财经 →</strong></a>${reports[0]?`<p class="latest-daily">最新一期：<a href="finance/daily/${reports[0].date}.html">${reports[0].date} · ${esc(reports[0].title)}</a></p>`:''}<!-- DAILY-FINANCE-END -->`;
if(finance.includes('<!-- DAILY-FINANCE-START -->'))finance=finance.replace(/<!-- DAILY-FINANCE-START -->[\s\S]*?<!-- DAILY-FINANCE-END -->/,block);else finance=finance.replace(/(<section id="articles" class="category-content">)[\s\S]*?(<\/section><\/div><div class="next-chapter">)/,'$1'+block+'$2');fs.writeFileSync(path.join(root,'finance.html'),finance);
console.log(`Built ${reports.length} daily reports, archive and finance entry.`);
